import { Injectable, Logger } from '@nestjs/common';

/**
 * Lazy Puppeteer wrapper. Chromium is not bundled by default — install via
 * `npm i puppeteer` (already in deps) and on Railway add Chromium pkg in
 * `nixpacks.toml` (see deployment README).
 *
 * Falls back to returning the HTML as a Buffer when Chromium is unavailable
 * so reports can still be rendered server-side as `.html` for now.
 */
@Injectable()
export class PdfService {
  private readonly logger = new Logger(PdfService.name);
  private browserPromise: Promise<any> | null = null;

  private async getBrowser() {
    if (!this.browserPromise) {
      this.browserPromise = (async () => {
        // eslint-disable-next-line @typescript-eslint/no-var-requires
        const puppeteer = require('puppeteer');
        return puppeteer.launch({
          headless: 'new',
          args: ['--no-sandbox', '--disable-setuid-sandbox'],
        });
      })().catch((err) => {
        this.logger.warn(`Puppeteer unavailable, falling back to HTML output: ${err.message}`);
        this.browserPromise = null;
        return null;
      });
    }
    return this.browserPromise;
  }

  async render(html: string): Promise<{ buffer: Buffer; contentType: string; ext: 'pdf' | 'html' }> {
    const browser = await this.getBrowser();
    if (!browser) {
      return {
        buffer: Buffer.from(html, 'utf8'),
        contentType: 'text/html',
        ext: 'html',
      };
    }
    const page = await browser.newPage();
    try {
      await page.setContent(html, { waitUntil: 'networkidle0' });
      const pdf: Buffer = await page.pdf({
        format: 'A4',
        printBackground: true,
        margin: { top: '20mm', right: '15mm', bottom: '20mm', left: '15mm' },
        displayHeaderFooter: true,
        footerTemplate:
          '<div style="font-size:9px;width:100%;text-align:center;color:#6b7280;padding:0 15mm">' +
          'Generated by Steward · Page <span class="pageNumber"></span> of <span class="totalPages"></span>' +
          '</div>',
        headerTemplate: '<span></span>',
      });
      return { buffer: pdf, contentType: 'application/pdf', ext: 'pdf' };
    } finally {
      await page.close();
    }
  }
}
