import { Injectable } from '@nestjs/common';
import { AuditService } from '../audit/audit.service';

/**
 * ReportsService — generates HTML/PDF reports via Puppeteer.
 * AWS S3 upload is prepared but commented out until S3 credentials are configured.
 */
@Injectable()
export class ReportsService {
  constructor(private readonly auditService: AuditService) {}

  /**
   * Generate an HTML string for a portfolio screening report.
   * In production this is passed to Puppeteer to produce a PDF.
   */
  buildPortfolioReportHtml(data: {
    advisorName: string;
    firmName: string;
    fspNumber?: string;
    logoUrl?: string;
    primaryColour?: string;
    clientName: string;
    date: string;
    screening: any;
  }): string {
    const colour = data.primaryColour ?? '#1e40af';
    const categories = (data.screening.by_category ?? [])
      .map(
        (c: any) =>
          `<tr>
            <td style="padding:8px;border-bottom:1px solid #e5e7eb;text-transform:capitalize">${c.category}</td>
            <td style="padding:8px;border-bottom:1px solid #e5e7eb">${c.exposure_pct.toFixed(2)}%</td>
            <td style="padding:8px;border-bottom:1px solid #e5e7eb">${c.affected_funds_count}</td>
          </tr>`,
      )
      .join('');

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <style>
    body { font-family: Arial, sans-serif; color: #111827; margin: 0; padding: 40px; }
    .header { border-bottom: 3px solid ${colour}; padding-bottom: 16px; margin-bottom: 32px; display: flex; justify-content: space-between; align-items: center; }
    .firm { font-size: 22px; font-weight: bold; color: ${colour}; }
    .score-box { border: 2px solid ${colour}; border-radius: 8px; padding: 24px; text-align: center; margin: 24px 0; }
    .score-clean { font-size: 48px; font-weight: bold; color: #16a34a; }
    .score-compromised { font-size: 48px; font-weight: bold; color: #dc2626; }
    table { width: 100%; border-collapse: collapse; margin-top: 16px; }
    th { background: ${colour}; color: white; padding: 10px; text-align: left; }
    .footer { margin-top: 48px; font-size: 10px; color: #6b7280; border-top: 1px solid #e5e7eb; padding-top: 12px; }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <div class="firm">${data.firmName}</div>
      ${data.fspNumber ? `<div style="font-size:12px;color:#6b7280">FSP: ${data.fspNumber}</div>` : ''}
    </div>
    ${data.logoUrl ? `<img src="${data.logoUrl}" style="height:60px" />` : ''}
  </div>

  <h1 style="color:${colour}">Portfolio Screening Report</h1>
  <p><strong>Client:</strong> ${data.clientName}</p>
  <p><strong>Date:</strong> ${data.date}</p>
  <p><strong>Advisor:</strong> ${data.advisorName}</p>
  <p><strong>Mode:</strong> ${data.screening.mode}</p>

  <div class="score-box">
    <div style="display:flex;justify-content:space-around">
      <div>
        <div class="score-clean">${data.screening.clean_pct?.toFixed(1)}%</div>
        <div>Clean</div>
      </div>
      <div>
        <div class="score-compromised">${data.screening.compromised_pct?.toFixed(1)}%</div>
        <div>Compromised</div>
      </div>
    </div>
  </div>

  ${
    categories
      ? `<h2>Category Exposure</h2>
  <table>
    <thead><tr><th>Category</th><th>Exposure %</th><th>Funds Affected</th></tr></thead>
    <tbody>${categories}</tbody>
  </table>`
      : ''
  }

  <div class="footer">
    This report is generated by the Steward platform and is intended for advisor use only. It does not constitute financial advice. 
    Advice is regulated in terms of the Financial Advisory and Intermediary Services Act (FAIS).
    Prepared by: ${data.firmName} | FSP: ${data.fspNumber ?? 'N/A'}
  </div>
</body>
</html>`;
  }

  async generatePortfolioReport(
    advisorId: string,
    reportData: Parameters<ReportsService['buildPortfolioReportHtml']>[0],
  ): Promise<{ html: string; message: string }> {
    const html = this.buildPortfolioReportHtml(reportData);
    await this.auditService.log(advisorId, 'report.generated', 'report', undefined, {
      client: reportData.clientName,
      type: 'portfolio_screening',
    });
    return {
      html,
      message: 'Report HTML generated. Use Puppeteer in production to render as PDF.',
    };
  }
}
